# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nazarpotipaka/CLionProjects/cserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nazarpotipaka/CLionProjects/cserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nazarpotipaka/CLionProjects/cserver/CMakeFiles /Users/nazarpotipaka/CLionProjects/cserver/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nazarpotipaka/CLionProjects/cserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cserver

# Build rule for target.
cserver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cserver
.PHONY : cserver

# fast build rule for target.
cserver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/build
.PHONY : cserver/fast

App/Kernel.o: App/Kernel.cpp.o

.PHONY : App/Kernel.o

# target to build an object file
App/Kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/App/Kernel.cpp.o
.PHONY : App/Kernel.cpp.o

App/Kernel.i: App/Kernel.cpp.i

.PHONY : App/Kernel.i

# target to preprocess a source file
App/Kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/App/Kernel.cpp.i
.PHONY : App/Kernel.cpp.i

App/Kernel.s: App/Kernel.cpp.s

.PHONY : App/Kernel.s

# target to generate assembly for a file
App/Kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/App/Kernel.cpp.s
.PHONY : App/Kernel.cpp.s

Deps/Request.o: Deps/Request.cpp.o

.PHONY : Deps/Request.o

# target to build an object file
Deps/Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Request.cpp.o
.PHONY : Deps/Request.cpp.o

Deps/Request.i: Deps/Request.cpp.i

.PHONY : Deps/Request.i

# target to preprocess a source file
Deps/Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Request.cpp.i
.PHONY : Deps/Request.cpp.i

Deps/Request.s: Deps/Request.cpp.s

.PHONY : Deps/Request.s

# target to generate assembly for a file
Deps/Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Request.cpp.s
.PHONY : Deps/Request.cpp.s

Deps/Response.o: Deps/Response.cpp.o

.PHONY : Deps/Response.o

# target to build an object file
Deps/Response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Response.cpp.o
.PHONY : Deps/Response.cpp.o

Deps/Response.i: Deps/Response.cpp.i

.PHONY : Deps/Response.i

# target to preprocess a source file
Deps/Response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Response.cpp.i
.PHONY : Deps/Response.cpp.i

Deps/Response.s: Deps/Response.cpp.s

.PHONY : Deps/Response.s

# target to generate assembly for a file
Deps/Response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Response.cpp.s
.PHONY : Deps/Response.cpp.s

Deps/Router.o: Deps/Router.cpp.o

.PHONY : Deps/Router.o

# target to build an object file
Deps/Router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Router.cpp.o
.PHONY : Deps/Router.cpp.o

Deps/Router.i: Deps/Router.cpp.i

.PHONY : Deps/Router.i

# target to preprocess a source file
Deps/Router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Router.cpp.i
.PHONY : Deps/Router.cpp.i

Deps/Router.s: Deps/Router.cpp.s

.PHONY : Deps/Router.s

# target to generate assembly for a file
Deps/Router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Router.cpp.s
.PHONY : Deps/Router.cpp.s

Deps/Utils.o: Deps/Utils.cpp.o

.PHONY : Deps/Utils.o

# target to build an object file
Deps/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Utils.cpp.o
.PHONY : Deps/Utils.cpp.o

Deps/Utils.i: Deps/Utils.cpp.i

.PHONY : Deps/Utils.i

# target to preprocess a source file
Deps/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Utils.cpp.i
.PHONY : Deps/Utils.cpp.i

Deps/Utils.s: Deps/Utils.cpp.s

.PHONY : Deps/Utils.s

# target to generate assembly for a file
Deps/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/Deps/Utils.cpp.s
.PHONY : Deps/Utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserver.dir/build.make CMakeFiles/cserver.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cserver"
	@echo "... App/Kernel.o"
	@echo "... App/Kernel.i"
	@echo "... App/Kernel.s"
	@echo "... Deps/Request.o"
	@echo "... Deps/Request.i"
	@echo "... Deps/Request.s"
	@echo "... Deps/Response.o"
	@echo "... Deps/Response.i"
	@echo "... Deps/Response.s"
	@echo "... Deps/Router.o"
	@echo "... Deps/Router.i"
	@echo "... Deps/Router.s"
	@echo "... Deps/Utils.o"
	@echo "... Deps/Utils.i"
	@echo "... Deps/Utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

